### ISSUE TITLE
WMIC open error

### ISSUE THREAD

**Issue by Nulliik** [Haidra-Org/AI-Horde#179]
During startup ray resource_spec.py is executed. Error happens in lines 286-287. For some reasons wmic does not execute and windows returns with Error 2 file not found. I tried adding it to path and was able to run command with cmd instance opened by myself. For fixing it for myself i just set return value to 1, but it is no good solution. AI-Horde folder is located at another disk if it helps.

**Comment by tazlin** [comment]
This appears to be a stale issue. If the issue is not resolved feel free to reopen.
