### ISSUE TITLE
It seems sqlite JSON not support has_key() method

### ISSUE THREAD

**Issue by brain-zhang** [Haidra-Org/AI-Horde#248]
It seems Only PostgreSQL(JSONB) support `has_key()` and `astext()` method

https://github.com/Haidra-Org/AI-Horde/blob/8fb4ad5bf9f7ea3f10433ea7af5310d9d5fb7500/horde/database/functions.py#L697

maybe horde server should Dropping support for sqlite;

**Comment by db0** [comment]
Sqlite was only ever for really quick local development and testing, not for production purposes.

**Comment by brain-zhang** [comment]
Thank you for your patient response;
But now i deployed AI-Horde Server locally with sqlite; It'll rasie Error when i submit a job;

<img width="1393" alt="image" src="https://github.com/Haidra-Org/AI-Horde/assets/1989073/ee21504d-e352-4d70-9474-801eb131e49b">


Perhaps we should emphasize in the Readme file that sqlite is for testing purposes only and does not actually work;

**Comment by db0** [comment]
Yes, that should be emphasized. Theoretically we could adjust shese methods to use alternatives as I've dfone with the classes, but it's a lot of work I don't have time for atm,
