### ISSUE TITLE
To avoid abuse, untrusted users can only have up to 3 distinct workers. (403)

### ISSUE THREAD

**Issue by curtmgray** [Haidra-Org/AI-Horde#266]
I'm getting the below error when running the scribe worker

To avoid abuse, untrusted users can only have up to 3 distinct workers. (403)

How can I manage my distinct workers? I'm only running one so I must have some duplicates or something weird going on.

**Comment by db0** [comment]
In the API you can see and delete your workers, but there's a few UI implementations. I believe lite.koboldai.net allows you to do it and you should also be able to see and delete them from https://aqualxx.github.io/stable-ui/dashboard
