### ISSUE TITLE
Tiling option does not work (disabled?)

### ISSUE THREAD

**Issue by Kryptortio** [Haidra-Org/AI-Horde#267]
I have tried using the Tiling option with two clients and a couple of different options but it only returns the error 

> No available workers can fulfill this request.

I think maybe it has been disabled for some reason? Possibly [here](https://github.com/Haidra-Org/AI-Horde/blob/249374736c44b2e39c92b0825a057b04bdebb2fc/horde/bridge_reference.py#L14) but I'm just guessing as I'm not familiar with the code.

**Comment by tazlin** [comment]
Tiling is currently not supported on the horde. If or when it becomes a feature of comfyui, it is possible it will be supported then.

**Comment by Kryptortio** [comment]
Thanks for the information, did not know that ComfyUI was used by stable horde. Looks like there has been [some work](https://github.com/comfyanonymous/ComfyUI/issues/646) on this recently so hopefully it can be fixed soon (otherwise I guess it should be removed from the clients but that would be a shame).
