### ISSUE TITLE
how to load an alternative version of a lora

### ISSUE THREAD

**Issue by indonsfw** [Haidra-Org/AI-Horde#270]
Hello all..

if i want to load a lora from civitai com/models/98142/indonesiadoll-likeness, i can just add a **_"loras": [{"name": "98142" blah blah_** to my Json request.

but how to load the subversion of a lora from civit like this civitai com/models/98142?**modelVersionId=104948**

please help me, very big thanks..

**Comment by Efreak** [comment]
Horde only supports the latest version of a Lora

**Comment by db0** [comment]
Yes, we don't support people using the version field in a non-standard manner
