### ISSUE TITLE
Webhook notifications upon job completion

### ISSUE THREAD

**Issue by SamKingDev** [Haidra-Org/AI-Horde#271]
The ability for the horde to notify us upon completion of a generation would be invaluable.

We would need a new API route to set up the webhook. Potentially, one could be dedicated for text generations and another for image generations. An example route might look like /api/webhook/(image | text)/complete. This structure would also accommodate additional webhooks for other events in the future if necessary.

A likely payload structure might be:

```json
{
  "URL": "https://localhost:3000/api/webhook...",
  "Secret": "a1e231b0..."
}
```

Then, whenever a job is completed (or potentially if it fails), that webhook will be invoked. The provided secret will be sent in a header, allowing for validation of the request to ensure it originated from the horde. The payload received would be similar to what is returned from the generation status endpoint, making it straightforward for users to process.

```json
{
  "id": "123...",
  "finished": 0,
  "processing": 0,
  "restarted": 0,
  "waiting": 0,
  "done": true,
  "faulted": false,
  "wait_time": 0,
  "queue_position": 0,
  "kudos": 0,
  "is_possible": true,
  "generations": [
    {
      "worker_id": "string",
      "worker_name": "string",
      "model": "string",
      "state": "ok",
      "img": "string",
      "seed": "string",
      "id": "string",
      "censored": true
    }
  ],
  "shared": true
}
```

**Comment by scenaristeur** [comment]
i have worked on a decentralized task system executor based on yjs https://scenaristeur.github.io/ypu/
and it could work with python with https://davidbrochart.github.io/ypy-websocket/ 

but i don't know how to manage this "on event" part in python
```
     # Changes to remote ydoc are applied to local ydoc.
        # Changes to local ydoc are sent over the WebSocket and
        # broadcast to all clients.
```

on this client  https://davidbrochart.github.io/ypy-websocket/usage/client/
