### ISSUE TITLE
Rate limiting is on a per-JobID basis

### ISSUE THREAD

**Issue by tazlin** [Haidra-Org/AI-Horde#272]
The desired rate limit for check, for example:

https://github.com/Haidra-Org/AI-Horde/blob/018e350e81f20f4740bdbd1d3dd022f81f91dd0d/horde/apis/v2/stable.py#L312

Is in practice governed by: 

https://github.com/Haidra-Org/AI-Horde/blob/018e350e81f20f4740bdbd1d3dd022f81f91dd0d/horde/apis/v2/base.py#L101-L103

This function returns a value such as `'127.0.0.1@GET@/api/v2/generate/check/9267a341-554a-4f99-a7bc-9de2007518a5'` (from my local testing instance).

In practice, this means the rate limit happens on per job ID basis. Is this intended?

**Comment by db0** [comment]
Yes.
