### ISSUE TITLE
ControlNet Slows Down KSampler?

### ISSUE THREAD

**Issue by PaulFidika** [Haidra-Org/AI-Horde#276]
I've noticed that KSampler time to complete increases 2x or 3x with one ControlNet applied, and increases 10x with two ControlNets applied. I'm wondering if this is expected behavior, or if this is an error in my setup? Is this because the conditioning being applied is significantly more complex?

**Comment by db0** [comment]
Yes, ControlNets make things significantly slower. I can't tell you the exact reasons as I'm not an expert on this
