### ISSUE TITLE
FR: support for Loras and TIs by version

### ISSUE THREAD

**Issue by Efreak** [Haidra-Org/AI-Horde#286]
It would be nice to see support for sending a modelVersionId for Loras and TIs instead of just the Lora id. This is an issue that comes up occasionally both on Horde discord and on other discords I'm in when people want to use a specific version of a Lora or TI.

Despite not being the intended use by Civitai, several of the most popular TIs are groups of related items listed as versions of a single item (the age slider is one). Beyond that, some older models work better than newer models, and some have versions available with more or less training than the primary version. There's also a number of collections of items that are entirely unrelated and where the author doesn't care enough about them to make individual releases; some of these explicitly state that they were trained for personal use and only made available by request.

**Comment by tazlin** [comment]
This was fixed as of https://github.com/Haidra-Org/AI-Horde/pull/337.

**Comment by db0** [comment]
Well, halfway. TIs don't support versions still, but I think we have another issue for this already
