### ISSUE TITLE
CSAM ban should probably cancel queued files

### ISSUE THREAD

**Issue by Maeyanie** [Haidra-Org/AI-Horde#300]
I've noticed what some people do to generate CSAM files is submit a huge batch of them. The detector will pick up many, but not everything. The person will get banned for it, but the rest of the batch will finish anyhow, still giving the person a fair bit of illegal content.

Instead, when the ban happens, it would probably be best to cancel all the other jobs submitted by that person.

**Comment by db0** [comment]
We do not ban based on the CSAM detector, as it has a fair bit of false positive rate. The idea, along with the regex scanner is to discourage those trying to generate such content. There is no perfect solution but the amount that would slip through should be extraordinarily small if any.

**Comment by Maeyanie** [comment]
Ah, my mistake, the tooltip on one of the generators says it does, and fool that I am, I assumed it was telling the truth. :D

It's a lot more common than "extraordinarily small" though, I wouldn't have said anything if I hadn't noticed it being a problem. But you're right that there isn't really a better solution.

**Comment by db0** [comment]
Please PM us on discord. If there's specific prompts that are easily slipping through, we can tweak.

**Comment by Maeyanie** [comment]
I've deleted all of it I found, but next time I see it happen I'll do that. Thanks.
