### ISSUE TITLE
Support 'batch_size' (`n_iter` in comfyui)

### ISSUE THREAD

**Issue by tazlin** [Haidra-Org/AI-Horde#301]
For users who want multiple images where all the parameters are the same *except* seed, batch_size has obvious benefits from the AI-Horde's perspective:

### Rationale
- There is typically a small, but appreciable, speedup to inference when using n_iter in comfy. Where one image may take 3 seconds, 4 images may only take 8 or 9 seconds, depending on the card.
  - This is especially true with the worker's use of comfyui, as pipelines aren't 'cached', and run with more fixed wind up time than native comfyui.  
- With network overhead, users would in many situations get all of the requested images back sooner and while consuming less horde compute. (and a correspondingly lower kudos cost) 

### Proposed Job Dispatch Logic
Of note, there is a cut off on efficiency for most cards at around 4 images at 512x512 and 2 images at 1024x1024 for many low-to-medium-low grade cards. Accordingly, an ideal initial implementation would:

- Assign a random seed, if the request has none.
- Break up the batch_size requests 
  - For 512x512 - 768x768
     - Any batch_size of 4 or less gets sent to a worker immediately.
     - Any batch_size of 5 or greater is divided accordingly:
        - Group 1 is given the initial seed, and 1 (batch_size 4) job is dispatched to a single worker.
        - Group 2 is given the initial seed plus 4, and 1 (batch_size 4) job is dispatched to a single worker.
        - etc...
  - For greater than 768x768, the same, but in groups of two.

Alternatively, requests of <768 could be limited to 4 batch_size, and >768 limited to 2, to start, and we can explore more complex handling in the future.

### Other Concerns

- The API would also need to generate and provide to workers an appropriate number of upload links, and correspondingly notify the user of them.
- The kudo's model would need to be retrained to account for this new dynamic.

### Related 
- https://github.com/Haidra-Org/hordelib/issues/83
- https://github.com/Haidra-Org/horde-worker-reGen/issues/24

**Comment by db0** [comment]
Functionality Added
