### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by FishyMine** [Haidra-Org/AI-Horde#305]
Just installed AI Horde, but I cant even run it.

There aren't any errors, and I am using Tesla K80 24GB for the processing. 

The benchmark doesn't start, it just loads diffusion then crashes.

**Comment by tazlin** [comment]
8/10 times this is because you are on an HDD. The `logs/bridge.log` file may have more information.

Generally speaking, you will find more and more immediate support on this discord, https://discord.gg/MXEX4ZhWGV.

**Comment by FishyMine** [comment]
I'm not on a HDD..

**Comment by FishyMine** [comment]
> 8/10 times this is because you are on an HDD. The `logs/bridge.log` file may have more information.
> 
> Generally speaking, you will find more and more immediate support on this discord, https://discord.gg/MXEX4ZhWGV.

TEAMGROUP MP33 M.2 SSD

**Comment by FishyMine** [comment]
and nobody responds on the discord

**Comment by tazlin** [comment]
The project is run entirely by volunteers. You have to give some time, consideration and patience to those who may be willing to respond and help. It appears you gave around 1 minute for someone to respond. Please be patient.

**Comment by FishyMine** [comment]
> The project is run entirely by volunteers. You have to give some time, consideration and patience to those who may be willing to respond and help. It appears you gave around 1 minute for someone to respond. Please be patient.

ERROR      | 2023-10-19 11:33:14.591286 | worker.workers.stable_diffusion:run_pilot_job:236 - Failed to run a basic inference job. This is a critical error.
ERROR      | 2023-10-19 11:33:14.591286 | worker.workers.stable_diffusion:run_pilot_job:245 - It is very likely the worker is not configured correctly for this system.
ERROR      | 2023-10-19 11:33:14.591286 | worker.workers.stable_diffusion:run_pilot_job:245 - Consider lowering your `max_power` in your bridgeData.
ERROR      | 2023-10-19 11:33:14.591286 | worker.workers.stable_diffusion:run_pilot_job:245 - With `max_power` set to 8, the max resolution this worker would process is 512x512.
ERROR      | 2023-10-19 11:33:14.591286 | worker.workers.stable_diffusion:run_pilot_job:245 - You can also ask the developers in the official discord for help.
