### ISSUE TITLE
loosen/refocus Stop Sequence limits

### ISSUE THREAD

**Issue by RossAscends** [Haidra-Org/AI-Horde#312]
re: https://github.com/Haidra-Org/AI-Horde/pull/311

Currently stop sequences are set to a maximum of 16 individual sequences, but this limit can often be reached very quickly if the user tries to include all likely variations of a target token sequence.

Example: 
```
\ncharname: <-- how it actually appears in chat
\nCharname: <-- capitalized version
\n charname: <-- leading space
\n Charname: <-- leading space capitalized
Charname: <--
charname: <--   same as above just without a newline
 Charname: <--
 charname: <--
```

So that is 8 sequences just to safeguard against a single chat member being improperly impersonated. 

Suggest to remove the limitation on the number of individual sequences and instead put the limit on total characters.
Perhaps a sensible limit would be related to the worker's prompt token limit.

**Comment by LostRuins** [comment]
I think we can consider increasing the total sequence limit from 16 to 128, while keeping the max payload char length the same.

Reasoning is that ST is planning to create a hivemind mode that includes a lot of participants, and will need a few strings for each one.
