### ISSUE TITLE
Add support for LCM lora

### ISSUE THREAD

**Issue by db0** [Haidra-Org/AI-Horde#322]
https://huggingface.co/blog/lcm_lora

**Comment by tazlin** [comment]
As mentioned else where, this would benefit from [n_iter](https://github.com/orgs/Haidra-Org/projects/8) (`n` on the API), especially with high end cards.

Namely, a 4090 could likely do a 4 step image in sub-second time frames (<0.7 seconds according to the paper), but initializing a comfy pipeline takes longer than that. Workers would benefit in terms of efficiency being able to batch these jobs and users would get more images for less kudos.

**Comment by db0** [comment]
Correct. Batching is very much on my priority list. I'm hoping to get the NLNet funding to work on it soon.

**Comment by tazlin** [comment]
As of https://github.com/Haidra-Org/hordelib/commit/261b2595553af2c7c8d626a58115c219f181a311, the version of comfyui packaged supports LCM, and now hordelib needs the relevant changes to accept it, accounting for the fact it needs a certain sampler to work. (see [here for more info](https://github.com/comfyanonymous/ComfyUI/commit/002aefa382585d171aef13c7bd21f64b8664fe28#diff-ff903427b64d57103d983ee5eeb6c33ffb5ab760526a48a35ad42d5afafdf2fb)).

**Comment by tazlin** [comment]
This was resolved as of https://github.com/Haidra-Org/hordelib/pull/132 and https://github.com/Haidra-Org/AI-Horde/pull/337
