### ISSUE TITLE
Newline breaking terminal display

### ISSUE THREAD

**Issue by alx** [Haidra-Org/AI-Horde#334]
Hi,

There is a newline somewhen during the initialization process of horse-bridge.sh that breaks the terminal display, I'm not sure if it's only on my side or if other people have the same issue.

![Screenshot from 2023-12-16 13-27-36](https://github.com/Haidra-Org/AI-Horde/assets/373/f0c1c055-e818-4e46-b3e6-6c78a961ead6)

**Comment by tazlin** [comment]
Please update to https://github.com/Haidra-Org/horde-worker-reGen if you haven't already.
