### ISSUE TITLE
Allow use of other SDXL models up to 1024x1024 when heavy demand. Currently only covers the base model.

### ISSUE THREAD

**Issue by rbrtcs1** [Haidra-Org/AI-Horde#347]
https://github.com/Haidra-Org/AI-Horde/blob/cdf4b9dcbbff4f865c2bec0e5349ce7cc4917573/horde/classes/stable/waiting_prompt.py#L306

Looks like this check doesn't include newer sdxl models (notably AlbedoXL, but more in the future)

**Comment by db0** [comment]
Fixed
