### ISSUE TITLE
Allow shared key requests to go through when out of kudos (like a normal api key)

### ISSUE THREAD

**Issue by rbrtcs1** [Haidra-Org/AI-Horde#350]
Obviously tricky to handle the queue position correct (for a low-kudos account instead), and it might be useful as a flag (not sure of other people's use-cases)

**Comment by tazlin** [comment]
May be related to a solution to #365

**Comment by rbrtcs1** [comment]
Sort of - the problem here is that a request initiated with a shared key is denied if that key is out of kudos, even if the request would have been allowed as anonymous. 

#365 helps to ensure the request would be within the anonymous limits, but I’m not sure it would actually allow it to go through.

That being said - this isn’t a very important issue imo, as it’s easily circumvented by just using the anonymous account. (#365 would have a lot of uses though - and I assume it would be much easier to implement)
