### ISSUE TITLE
Inpainting stopped working

### ISSUE THREAD

**Issue by lbosk** [Haidra-Org/AI-Horde#351]
First of all, I must say that inpainting always worked to me up to some days ago.
Anyway today (with small images, stable_diffusion_inpainting or Deliberate inpaining as models, post-processing, loras and textual inversions disabled) I started getting the error "Currently no worker available to generate your image. Please try again later."
This should not be possible, because my own worker is active and these models are loaded as well.
How is it possible?

**Comment by tazlin** [comment]
Thanks for the report. It looks like this issue (which we were tangentially aware of through a separate issue) is something that ties into some changes made in the last couple of months, but only recently became apparent when something else changed. You can see the associated PR for more information. When #352 is closed, and the horde updated, this will be resolved.
