### ISSUE TITLE
Add option to change automatically the request requirements to stay within the upfront kudos limits

### ISSUE THREAD

**Issue by db0** [Haidra-Org/AI-Horde#365]
Just to prevent a straight up deny. Might be useful for things FOSS bots which are typically running at the developers account, but then someone tries to reuse with their own.

**Comment by Efreak** [comment]
Upfront kudos limit meaning the amount on the account, or an amount that the user specifies? The second one could actually be pretty useful as well for UIs that want to expose a lot of parameters but not make the user think about cost.
