### ISSUE TITLE
Batched jobs with post processing enabled don't have enough time to complete before being considered stale

### ISSUE THREAD

**Issue by tazlin** [Haidra-Org/AI-Horde#401]
With the recent implementation of batching and its now wider-spread use, it has become apparent that the job stale timeout is not long enough. Even some of the highest-end cards still consistently trigger the stale timeout even under the best of circumstances.

I propose:
- Any job with `n` > 1 and any amount of entries for `post-processing` be given more time proportional to the number of post-processors and images in the batch

**Comment by db0** [comment]
Fixed in https://github.com/Haidra-Org/AI-Horde/commit/d958a368957ef461156a0bff280dde63f7afc240. Tagged the wrong number
