### ISSUE TITLE
[REQUEST] Easy Setup guide for a Horde node, under linux

### ISSUE THREAD

**Issue by dlasher** [Haidra-Org/AI-Horde#41]
I suspect we'd have a lot more nodes if we had a quick/easy guide on how to take that machine with the older 2G/3G nvidia GPU, and bring it online to help the horde. Can we get a guide, and if one already exists, can we link it on the README?

Assume Ubuntu 20-22, since that seems to be the most common now?

**Comment by db0** [comment]
The quickest way is the documentation linked in the readme to install webui. What do you think could be improved?

**Comment by db0** [comment]
Well you can help with that. We have a permanent 25K bounty for making guidelines and videos for installing the worker ;)

**Comment by tazlin** [comment]
This issue appears to be stale. If you have any further problems, please feel free to open a new issue.
