### ISSUE TITLE
Create Application APIs

### ISSUE THREAD

**Issue by db0** [Haidra-Org/AI-Horde#42]
Normally IP can only be used by 3 user accounts at the same time. We should deploy an endpoint where a user can register an App Name and get an API key for it to increase this limit.

The application will be stored in the DB and will track how many users are using it. It will default to 1, but can be increased by admins and mods of the horde. Setting it to -1 will allow infinite amounts of accounts from the same IP

When this app key is sent along with the payload, it count as just 1 of the accounts per IP. So any number of requests from different accounts using an app, can be used and the app will count as just 1 IP. However only 1 app can be active per IP, so other ones might need to wait their turn, or figure out how to arrange for a common app account.

**Comment by tazlin** [comment]
This issue dates back to a different era of the horde. However, I believe that this was accomplished, more or less [in a later PR.](https://github.com/Haidra-Org/AI-Horde/pull/332).

Technically, we do not have a self-register endpoint (AI-Horde moderators have to add them) but I tend to believe that should continue to be the case. If you want to reopen the issue in the spirit of one day adding self-registration for service accounts, feel free.


- See also https://github.com/Haidra-Org/AI-Horde/pull/332
