### ISSUE TITLE
Jobs are dispatched to workers which upon submit no longer exist

### ISSUE THREAD

**Issue by tazlin** [Haidra-Org/AI-Horde#443]
My understanding is that the current intention is that workers who are assigned valid jobs (at least, at the time of assignment) should always be able to submit the result for the quoted kudos reward. If the user cancels the job or would timeout by decay (the 20-minute limit), the worker should still receive the reward. 

- In at least one reported case this happened across three consecutive jobs which I will address in regen (https://github.com/Haidra-Org/horde-worker-reGen/issues/255) 
- However, I do think that this is otherwise most likey a bug rooted in a race condition and should eventually be addressed

**Comment by db0** [comment]
Just to note that a cancelled job still allows the worker to submit as the DB entry is not deleted on cancel.

**Comment by tazlin** [comment]
That is only the expected behavior. It is currently possible to get the 'job not found error' and be unable to submit with some high regularity.

**Comment by db0** [comment]
I believe you but I wonder why, as the job TTL is reset on job pop.

**Comment by tazlin** [comment]
I only was guessing that cancellation is the reason. Something causes a fairly high number of these 'lost' jobs. You can readily find instances of it on your worker, I'm sure. I've seen it in the logs of every worker I've been sent too. I can resolve the worker pausing job pops (see the related issue) but I worry that this all adds up to a fair bit of wasted time and lost kudos.

**Comment by db0** [comment]
I think this is fixed after I found the bug of not resetting the request ttl on pop but only on submit
